Development
Appic-Solutions/Appic_Multiswap pull request #1
Opened 2024-05-16 20:01 UTC by ChitranshVashney

I have made functions for add tokens in canister and withdraw tokens from canister

2024-05-17 10:18 UTC, asjn3e requested changes

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  public type TokenActor = actor {
@ChitranshVashney what is this token actor for?

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
Chinu are you sure it is the best practice to keep a hashmap in a hashmap?

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _getTokenActorWithType(tokenId : Text, tokenType : Text) : TokenActorVariable {
@ChitranshVashney please add comments for all the functions

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _getTokenActorWithType(tokenId : Text, tokenType : Text) : TokenActorVariable {
@ChitranshVashney i think it would be easier to consider ICRC2 as ICRC1 since it will make your job also easier.
dont forget that all ICRC2 token standards also contain ICRC1 functions

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _transferFrom(tokenId : Text, tokenType : Text, caller : Principal, value : Nat) : async TransferReceipt {
@ChitranshVashney please add comments for all the functions and explain why they've been created

2024-05-17 10:18 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _transfer(tokenId : Text, tokenType : Text, caller : Principal, value : Nat) : async TransferReceipt {
@ChitranshVashney please add comments, for all the functions

2024-05-17 10:19 UTC, asjn3e commented
Hey chinu 2 things, 
1- i think it would be easier if you consider ICRC2 tokens as ICRC1 since they are compatible and it will make your work easier,
2- please add comments for all functions and explain why they are created for and also add comments for parts inside the functions

2024-05-17 11:17 UTC, ChitranshVashney commented on src/multiswap_backend/main.mo
> +  public type TokenActor = actor {
This tokenActor is for Dip20 tokens

2024-05-17 11:20 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  public type TokenActor = actor {
So please name them in an clear way, and dont for get to add comments for every part of code

2024-05-17 11:25 UTC, ChitranshVashney commented on src/multiswap_backend/main.mo
> +  private func _getTokenActorWithType(tokenId : Text, tokenType : Text) : TokenActorVariable {
check this post https://forum.dfinity.org/t/dip-20-transfer-msg-caller/30839

2024-05-17 11:30 UTC, ChitranshVashney commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
Yes because we are storing data of many users
like that, 
user1-> token1 ->amount1
             token2 ->amount2
             
user1-> tokenX ->amountX
             tokenY->amountY
             tokenZ ->amountZ

2024-05-17 12:39 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
But why is that, can we just keep a hashmap of array of tokens?
I just want to know which way is the best way?

2024-05-17 12:46 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _getTokenActorWithType(tokenId : Text, tokenType : Text) : TokenActorVariable {
https://forum.dfinity.org/t/dip-20-transfer-msg-caller/30839/3?u=asjn3e

2024-05-17 12:47 UTC, ChitranshVashney commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
I find this data structure best to store data in map form

2024-05-17 12:48 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  private func _getTokenActorWithType(tokenId : Text, tokenType : Text) : TokenActorVariable {
> @ChitranshVashney i think it would be easier to consider ICRC2 as ICRC1 since it will make your job also easier. dont forget that all ICRC2 token standards also contain ICRC1 functions

And what about this?

2024-05-17 12:50 UTC, ChitranshVashney commented
> Hey chinu 2 things, 1- i think it would be easier if you consider ICRC2 tokens as ICRC1 since they are compatible and it will make your work easier, 2- please add comments for all functions and explain why they are created for and also add comments for parts inside the functions

I will discuss all your concern after completing the whole canister code.

2024-05-17 12:52 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
But why chinu? i just want to know the reason and if it is the best way i will also start using it, but before that what is the reason for that?

2024-05-17 13:00 UTC, ChitranshVashney commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
- the outer hashmap manages user data, while the inner hashmap manages the tokens each user has locked. This makes the structure intuitive and easier to understand.
- hashmaps provide average O(1) time complexity for lookups, insertions, and deletions
- In dsa this is the best approach because it manage space complexity and time complexity eficiently

2024-05-17 13:02 UTC, asjn3e commented
> > Hey chinu 2 things, 1- i think it would be easier if you consider ICRC2 tokens as ICRC1 since they are compatible and it will make your work easier, 2- please add comments for all functions and explain why they are created for and also add comments for parts inside the functions
> 
> I will discuss all your concern after completing the whole canister code.

No problem just dont forget to add comments for the whole part of your code and push your code

2024-05-17 13:07 UTC, asjn3e commented on src/multiswap_backend/main.mo
> +  var userTokensLocked : HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>> = HashMap.HashMap<Principal, HashMap.HashMap<Principal, Nat>>(1, Principal.equal, Principal.hash);
Ok, fair enough

2024-05-22 03:36 UTC, asjn3e commented
@ChitranshVashney please add comments

2024-06-07 10:55 UTC, merged